name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn generate
