name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
  AWS_CLOUDFRONT: ${{ secrets.AWS_CLOUDFRONT }}

  GH_APP_ENV: production
  GH_APP_URL: "https://kejsrecipes.com/"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Generate
        run: yarn generate
        env:
          NODE_ENV: production

      - name: Github Deployment - Start
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.GH_APP_ENV }}
          ref: ${{ github.ref }}

      - name: Upload
        uses: docker://amazon/aws-cli:2.1.6
        with:
          args: s3 sync dist s3://${{ env.AWS_BUCKET }} --sse AES256 --follow-symlinks --delete

      - name: Deploy
        uses: docker://amazon/aws-cli:2.1.6
        with:
          args: cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT }} --paths /*

      - name: Github Deployment - Update
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env_url: ${{ env.GH_APP_URL }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
