name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: ./dist/
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
